# Generated by Django 5.2.17 on 2026-08-18 03:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên kênh')),
                ('channel_type', models.CharField(choices=[('facebook', 'Facebook'), ('email', 'Email'), ('tiktok', 'TikTok'), ('website', 'Website'), ('other', 'Khác')], default='other', max_length=20, verbose_name='Loại kênh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Kênh truyền thông',
                'verbose_name_plural': 'Kênh truyền thông',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên chiến dịch')),
                ('objective', models.TextField(verbose_name='Mục tiêu')),
                ('audience', models.TextField(verbose_name='Đối tượng mục tiêu')),
                ('product', models.CharField(max_length=200, verbose_name='Sản phẩm/dịch vụ')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ngân sách')),
                ('status', models.CharField(choices=[('planned', 'Đã lập kế hoạch'), ('active', 'Đang chạy'), ('paused', 'Tạm dừng'), ('completed', 'Đã kết thúc'), ('archived', 'Lưu trữ')], default='planned', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chiến dịch marketing',
                'verbose_name_plural': 'Chiến dịch marketing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('body', models.TextField(verbose_name='Nội dung')),
                ('content_type', models.CharField(default='post', max_length=30, verbose_name='Định dạng')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('pending_review', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('published', 'Đã đăng')], default='draft', max_length=20, verbose_name='Trạng thái duyệt')),
                ('source', models.CharField(choices=[('manual', 'Con người viết'), ('ai', 'AI sinh')], default='manual', max_length=10, verbose_name='Nguồn')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm đăng')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_marketing_contents', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='campaigns.campaign')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='campaigns.channel')),
            ],
            options={
                'verbose_name': 'Nội dung marketing',
                'verbose_name_plural': 'Nội dung marketing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField(verbose_name='Ngày ghi nhận')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Lượt click')),
                ('conversions', models.PositiveIntegerField(default=0, verbose_name='Lượt chuyển đổi')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Chi phí')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='campaigns.campaign')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='campaigns.channel')),
            ],
            options={
                'verbose_name': 'Chỉ số chiến dịch',
                'verbose_name_plural': 'Chỉ số chiến dịch',
                'ordering': ['-metric_date', 'channel__name'],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'channel', 'metric_date'), name='unique_campaign_channel_metric_day')],
            },
        ),
    ]
